// angular 6/welcome-app/src/parent/star.component.ts
import { Component, Input, OnInit, Output, EventEmitter} from '@angular/core';

@Component({
    selector: 'st-star',
    templateUrl: './star.component.html',
})
export class StarComponent implements OnInit{
    count:number=0;
    @Input()
    num:number;
    @Output()
    starHovered:EventEmitter<Object>=new EventEmitter();
    ngOnInit(){
        console.log(this.num);
    }
    hover(){
        this.count++;
        this.starHovered.emit(this.count);
    }
}
<link data-require="bootstrap-css@3.3.6" data-semver="3.3.6" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" />
<div style="overflow:hidden" [style.width.px]="14*num" [style.height.px]="14">    
    <div style="overflow:hidden" [style.width.px]="14*5" (mouseover)="hover()">
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
    </div>
</div>

// reactJS/acme-product-management/src/starComponent.js
import React, { Component } from 'react';
import ReactTooltip from 'react-tooltip'
export default class StarComponent extends Component {
    render() {
        var jsx = (
            <div style={{ padding: '2px' }}>
            <link data-require="bootstrap-css@3.3.6" data-semver="3.3.6" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" />
                <div data-tip={this.props.rating+' stars'} style={{ overflow: 'hidden', textAlign: 'center', width: 14 * this.props.rating, height: 22 }} >
                    <div style={{overflow: 'hidden', width: 14 * this.props.rating, height: 22 }} >
                        <span className="glyphicon glyphicon-star"></span>
                        <span className="glyphicon glyphicon-star"></span>
                        <span className="glyphicon glyphicon-star"></span>
                        <span className="glyphicon glyphicon-star"></span>
                        <span className="glyphicon glyphicon-star"></span>
                    </div>
                </div>
                <ReactTooltip place='right'/>
            </div>
        );
        return jsx;
    }
}
