// angular 6/welcome-app/src/blue-button-game/blueButtonGame.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'st-blueButton',
    templateUrl: './blueButtonGame.component.html',
})
export class BlueButtonGame {
    blueButton: number;
    reset: boolean;
    i: number;
    msg:String;
    attempts: number = 4;
    btnStyle: any[25] = [];
    disable:boolean;
    constructor() {
        this.reset = false;
        this.disable=false;
        this.blueButton = Math.floor(Math.random() * (25) + 1);
        for (this.i = 0; this.i <= 25; this.i++) {
            this.btnStyle[this.i] = { 'background-color': 'grey', color:'white'};
        }
    }

    buttons: number[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25];
    buttonClick(id: number): void {
        this.btnStyle[id] = {
            'background-color': id > this.blueButton ? 'green' : id == this.blueButton ? 'blue' : 'red',
            'pointer-events': 'none',
            'color':'white'
        };
        this.attempts--;
        if(id==this.blueButton){
            this.msg="YOU WIN!";
            this.reset = true;
            return;
        }
        if (this.attempts == 0) {
            this.msg="game over you lose!";
            this.reset = true
            this.disable=true;
            this.btnStyle[this.blueButton]={
                'background-color':'blue',
                'color':'white'
            }
            return;
        }
        
    }
    resetClick(): void {
        window.location.reload();
    }
}
<style>
     input[type=button] {
            border-radius: 50%;
            background-color: grey;
            width: 90px;
            height: 90px;
        }
        .resetBtn {
            background-color: red;;
            color: white;
            width: 90px;
            height: 60px;
            cursor: pointer;
        }
</style>
<div>
    <h1 [style.color]="'blue'"> Blue Button Game</h1>
</div>
<div>
    Attempts Left:{{attempts}}
</div>
<div>
    <b *ngFor="let b of buttons;let i = index">
        <input [disabled]="disable" [ngStyle]="btnStyle[i]" type="button" value="{{i+1}}" (click)="buttonClick(i)">
        <br *ngIf="(i+1)%5==0">
    </b>
</div>
<h1>{{msg}}</h1>
<br>
<button class="resetBtn" (click)="resetClick()" *ngIf="reset">RESET</button>

// reactJS/welcome-app/src/blueButtonGameComponent.js
import React, { Component } from 'react';
export default class BlueButtonGameComponent extends Component {
    buttons = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25];
    gameOver = false;

    msg;
    a = [];
    constructor() {
        super();
        var blueBtn1 = Math.floor(1 + Math.random() * (25 - 1));
        this.state = {
            attempts: 5,
            blueBtn: blueBtn1
        }

    }

    click = (btn) => {
        var attempts1 = this.state.attempts;
        attempts1--;
        this.setState({
            attempts: attempts1
        });
        var col = this.state.blueBtn === btn ? 'blue' : btn < this.state.blueBtn ? 'red' : 'green';
        this.a[btn] = {
            backgroundColor: col,
            pointerEvents: 'none',
        }
        if (this.state.blueBtn === btn) {
            this.gameOver = true;
            this.msg = "you win!";
        }
        else if (this.state.attempts <= 1) {
            this.gameOver = true;
            this.msg = "Game Over, you lose!";
            this.a[this.state.blueBtn] = {
                backgroundColor: 'blue',
                pointerEvents: 'none'
            }
        }
    }
    reset() {
        window.location.reload();
    }
    render() {

        var buttons = this.buttons.map(function (btn) {
            return (
                <span>
                    <button onClick={() => { this.click(btn) }} disabled={this.gameOver} style={this.a[btn]} className='btn'>{btn}</button>
                    {btn % 5 === 0 ? <br /> : null}
                </span>
            );
        }.bind(this));
        var jsx = (
            <div>
                <span>
                    <style>{`
                button {
                    background-color: grey;
                    width: 90px;
                    height: 90px;
                    margin:5px;
                    color:white;
                }
              `}</style>
                </span>
                <h3>Attempts Remaining: {this.state.attempts}</h3><br />
                {buttons}
                <span style={{ color: 'white', margin: '5px' }} className="btn btn-primary" hidden={!this.gameOver} onClick={this.reset.bind(this)}>Reset</span>
                <br />
                <h2>{this.msg}</h2>
            </div>);
        return jsx;
    }
}
