// reactJS/welcome-app/src/primeNumberComponent.js
import React, { Component } from 'react';
import PrimeNumberService from './primeNumberService';
export default class PrimeNumberComponent extends Component {
    _service;
    constructor() {
        super();
        this._service=new PrimeNumberService();
        this.state = {
            isNumberPrime: null
        }
    }

    numberChange = (e) => {
        var event = e.target.value;
        var isPrime=this._service.isNumberPrime(event);
        this.setState({
            isNumberPrime: isPrime
        });
    }
    render() {
        var jsx = (
            <div>
                is number prime?&nbsp;
                <input type='number' style={{ backgroundColor: this.state.isNumberPrime === null ? 'lightgrey' : this.state.isNumberPrime ? 'green' : 'red', color: 'white' }} onChange={this.numberChange} />
            </div>
        );
        return jsx;
    }
}

// angular 6/welcome-app/src/prime-number/primeNumber.component.ts
import { Component } from '@angular/core';
import {PrimeComponentService} from '../prime-number/PrimeComponentService';

@Component({
    selector: 'st-isPrime',
    templateUrl: './primeNumber.component.html',
})
export class PrimeNumberComponent {
    number1: number;
    isNumberPrime:number=3;
    constructor(private _primeService:PrimeComponentService){
        console.log("Service created");
    }
    isPrime(event) {
        this.isNumberPrime=this._primeService.isPrime(event);
    }
}
<div>
    is number prime?
    <input type="text" [style.color]="'white'" [style.background-color]="isNumberPrime==0?'green':isNumberPrime==3?'yellow':'red'"
        [ngModel]='number1' (ngModelChange)='isPrime($event)'>
</div>
